spring:
  application:
    name: special-lecture

  datasource:
    hikari:
      password:
      username: sa
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
